version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: us-central1-docker.pkg.dev/go-blog-app-1/blog-app/backend:latest
    container_name: backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  frontend:
    image: us-central1-docker.pkg.dev/go-blog-app-1/blog-app/frontend:latest
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  worker:
    image: us-central1-docker.pkg.dev/go-blog-app-1/blog-app/worker:latest
    container_name: worker
    depends_on:
      - postgres

  logging-agent:
    image: us-central1-docker.pkg.dev/go-blog-app-1/blog-app/logging-agent:latest
    container_name: logging-agent

volumes:
  postgres_data:
