services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: ${GAR_REGISTRY}/backend:${TAG_NAME}
    container_name: backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  frontend:
    image: ${GAR_REGISTRY}/frontend:${TAG_NAME}
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  worker:
    image: ${GAR_REGISTRY}/worker:${TAG_NAME}
    container_name: worker
    depends_on:
      - postgres

  logging-agent:
    image: ${GAR_REGISTRY}/logging-agent:${TAG_NAME}
    container_name: logging-agent

volumes:
  postgres_data: