apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logging-agent
  namespace: ci-cd # Changed to ci-cd for consistency with other app components
spec:
  selector:
    matchLabels:
      app: logging-agent
  template:
    metadata:
      labels:
        app: logging-agent
    spec:
      # Associate with the KSA linked to the GSA with logging permissions
      serviceAccountName: app-workload-sa
      containers:
      - name: logging-agent
        image: logging-agent:latest
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

