apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: image-placeholder:latest # This will be replaced by the CI/CD pipeline
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "http://backend-service.ci-cd.svc.cluster.local:8080"
