apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: ci-cd
data:
  # These values should be updated to match your Cloud SQL instance
  DB_HOST: "10.0.0.1" # The Private IP of your Cloud SQL instance
  DB_PORT: "5432"
  DB_NAME: "blog-db" # The database name you configured in Terraform
  DB_USER: "YOUR_DB_USER" # The user for your Cloud SQL instance