apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: blogposts.demo.example.com
spec:
  group: demo.example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              title:
                type: string
              content:
                type: string
              createdAt:
                type: string
                format: date-time
  scope: Namespaced
  names:
    plural: blogposts
    singular: blogpost
    kind: BlogPost
    shortNames: [bp]